#
# Contains the full stack of the RTB4FREe stack (not including elk))
# Does contain zookeeper and kafka, postgres and minio
#
version: "3"

services:
  sqldb:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data
